export const getHealthKeywords = () => {
  const keywords = [
    "health",
    "wellness",
    "fitness",
    "vitality",
    "well-being",
    "disease",
    "illness",
    "sickness",
    "ailment",
    "malady",
    "cardiovascular",
    "respiratory",
    "digestive",
    "nervous",
    "musculoskeletal",
    "endocrine",
    "immune",
    "urinary",
    "reproductive",
    "allergy",
    "asthma",
    "cancer",
    "diabetes",
    "heart disease",
    "stroke",
    "arthritis",
    "depression",
    "anxiety",
    "obesity",
    "doctor",
    "physician",
    "nurse",
    "surgeon",
    "dentist",
    "therapist",
    "pharmacist",
    "chiropractor",
    "acupuncturist",
    "medication",
    "surgery",
    "therapy",
    "rehabilitation",
    "treatment",
    "cure",
    "prevention",
    "diagnosis",
    "prognosis",
    "symptom",
    "diagnosis",
    "treatment",
    "prevention",
    "cure",
    "recovery",
    "health insurance",
    "healthcare",
    "medical facility",
    "hospital",
    "clinic",
    "weak",
    "pandemic",
    "epidemic",
    "virus",
    "infection",
    "antibiotic",
    "vaccine",
    "immunization",
    "injury",
    "fracture",
    "wound",
    "nutrition",
    "diet",
    "mental health",
    "psychology",
    "psychiatry",
    "cardiology",
    "neurology",
    "oncology",
    "pediatrics",
    "geriatrics",
    "pharmaceutical",
    "immunology",
    "radiology",
    "orthopedics",
    "gynecology",
    "dermatology",
    "neurosurgery",
    "intensive care",
    "emergency room",
    "first aid",
    "hygiene",
    "public health",
    "disability",
    "chronic",
    "acute",
    "fatigue",
    "pain",
    "fit",
    " Headaches",
    "Fatigue",
    "Muscle aches and pains",
    "Yawning",
    "Sweating",
    "Fever",
    "Headache",
    "Eye Pain",
    "Breathing",
    "Heart rate",
    "Blood pressure",
    "Hunger and thirst",
    "sick",
  ];
  return keywords;
};
